# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ~/logstash-index:/var/lib/elasticsearch
  container_name: elkdocker_elk
  restart: always
  hostname: elk
  ports:
    - "514/udp:514/udp"
    - "5601:5601"
    - "9200:9200"
    - "9300:9300"
    - "5044:5044"
    - "5000:5000"
    - "5001:5001"
